title: TecnoNova
email: jean.sebastian12lloyd@gmail.com
description: "TecnoNova — El blog de innovación y tecnología"
baseurl: "/tecnonova"
url: "https://jeansebastian12lloyd-arch.github.io"
theme: minima
plugins: []
markdown: kramdown
author: Jean Sebastián Lloyd Zamora
